"""add stripe sub info

Revision ID: a819d83f4abf
Revises: 67cc006d50bf
Create Date: 2023-09-24 21:12:26.272910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a819d83f4abf'
down_revision: Union[str, None] = '67cc006d50bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_unique_constraint('stripe_id_unique', ['stripe_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('stripe_id_unique', type_='unique')
        batch_op.drop_column('stripe_subscription_status')
        batch_op.drop_column('stripe_id')

    # ### end Alembic commands ###
